### PR TITLE
Enhanced file renaming, more tokens

### PR DESCRIPTION
**Pull request by thomas-schultz**
I've made small changes how the renaming handles the tokens. My goal was to keep all existing tokens and their functionality, but add more options especially for Audio-Tags like language, codec, channels, etc.
I personally need these tags to distinguish between same movies/episodes with different languages. I did a little bit of testing, so for me it seems to work, but overall i have probably overseen some edge cases.

### CODE REVIEW

**Comment by ProIcons** [comment]
Hello and thank you for your contribution. Can you make a rebase merging all these commits into one ?

**Comment by mlaggner** [comment]
thanks for your contribution. will review it as soon as I have more time on my computer
could you do me a favor? could you also create the same changes for our upcoming V3 (branch v3)? Since there were massive changes in the renamer, you may have to redesign your changes a bit

@ProIcons there is now a squash and merge feature in github (https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) - so there is no need to do that as contributor any more ;)

**Comment by thomas-schultz** [comment]
Thanks for your advise.

The problem I had was that by now, tokens were only one character long. So, to add the possibility to address specific streams inside the media files, I had to change the regex of a token. I choose an approach were one token consists of '$' + multiple Letters + one or none Digit. If, for some reason the pattern should occur in the filename, the pattern can be terminated with pipe '|'.
I'm open for any feedback, because I do not know how other structure their media files.

I will have a look on the v3 branch for my changes, but I will probably take me at least this weekend.

**Comment by mlaggner** [comment]
the new token system is based on JMTE which we already use for export templates.
I did not have time to analyze your PR yet (I am busy too :D), but as far as I could read out of the comment above you had to change the token system?
To be honest - I would not like to change an existing system for the stable (v2) release, since such a change would not be recognized by many users until files become wrongly renamed :/

would it be okay, if we just try to put your changes to v3 (together), since I plan to force development for v3 and release it as soon as it is production ready?

I hope you understand my concerns

**Comment by thomas-schultz** [comment]
As far as I looked at the code, the new system makes my first approach (for v2) obsolete. Now, that i am aware of the new v3 branch, it really makes no sense to include these changes into v2.
It does not even have to be in the first release of v3, but I would be glad if, someday, I can stick with the upstream version, and am not bound to my fork forever.

**Comment by mlaggner** [comment]
okay, I will reject this PR and if you feel there should be an enhancement for v3 you can create a PR there

nevertheless - thanks for your effort

**Pull request closed without merging**
