### PR TITLE
Spelling: ID, IMDb, TheTVDB, URL, addition to translators, https

### PR DESCRIPTION
**Pull request by comradekingu**
As per https://en.wikipedia.org/wiki/IMDb and https://en.wikipedia.org/wiki/TheTVDB

### CODE REVIEW

**Comment by mlaggner** [comment]
thanks for your contribution.. 
in fact you've only changed some internal log infos and one UI occurrence of the Id naming ;)

what about the UI panel for movies? there is also a call to imdb/tmdb and labels with the Ids - are they ok?

**Comment by comradekingu** [comment]
@mlaggner Link?
I fix things a bit sporadically as I see them, it helps me finish the translation to Norwegian Bokmål.

**Comment by mlaggner** [comment]
here would be another location: https://github.com/tinyMediaManager/tinyMediaManager/blob/master/src/main/java/org/tinymediamanager/ui/movies/MovieDetailsPanel.java

btw: if you mean the translation via weblate, you have to look at the v3 branch (weblate is for v3 whereas transifex is for v2)

**Comment by mlaggner** [comment]
thanks for your contribution

**Pull request merged**
